sudo: false
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO=django17
  - DJANGO=django18
  - DJANGO=django19
  - DJANGO=django110
  - DJANGO=djangomaster

matrix:
  exclude:
    - python: "3.4"
      env: DJANGO=django17
    - python: "3.5"
      env: DJANGO=django17
  allow_failures:
    - env: DJANGO=djangomaster

before_install:
  - pip install codecov

install:
  - pip install tox

script:
  - TOX_TEST_PASSENV="TRAVIS TRAVIS_JOB_ID TRAVIS_BRANCH" tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO

after_success:
  - codecov
